import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { readFileSync, copyFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

/**
 * Figure out where to write main.js.
 *
 * Dev workflow: read `dev-config.json` (gitignored, per-developer) which holds
 * the absolute path to the developer's Obsidian vault. The build then emits
 * main.js straight into `<vault>/.obsidian/plugins/lmstudio-chat/`, so Obsidian
 * picks it up on the next reload with no manual copying.
 *
 * Fallback: if dev-config.json is missing, write to the project root (the
 * sample-plugin default). This keeps `npm run build` usable in CI / for
 * releases without a vault path.
 */
function resolveOutDir() {
	const pluginId = 'lmstudio-chat';
	try {
		const raw = readFileSync('dev-config.json', 'utf8');
		const { vaultPath } = JSON.parse(raw);
		if (!vaultPath) throw new Error('dev-config.json: vaultPath missing');
		return path.join(vaultPath, '.obsidian', 'plugins', pluginId);
	} catch {
		console.warn(
			'[esbuild] dev-config.json not found or invalid; writing main.js to project root.',
		);
		return '.';
	}
}

const outDir = resolveOutDir();
const outFile = path.join(outDir, 'main.js');

/**
 * Copy non-JS assets (manifest.json, styles.css) into the plugin output dir.
 * Obsidian needs manifest.json sitting next to main.js, or the plugin is
 * invisible. We do this on every build so the dev loop is self-contained.
 */
function copyAssets() {
	for (const asset of ['manifest.json', 'styles.css']) {
		if (existsSync(asset)) {
			copyFileSync(asset, path.join(outDir, asset));
		}
	}
}

copyAssets();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: outFile,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
